### ISSUE TITLE
ImportError: cannot import name '_C' from 'geo_parse'

### ISSUE THREAD

**Issue by SoniaQi** [mingliangzhang2018/PGDP#5]
I was running the line "from geo_parse.config import cfg," and it traced back to "from geo_parse import _C" and reported an error. The specific error message was "Traceback (most recent call last):
  File "[file_name].py", line 3, in <module>
    from demo.predictor import GeoDemo
  File "[path]/PGDP/demo/predictor.py", line 10, in <module>
    from geo_parse.modeling.detector import build_detection_model
  File "[path]/PGDP/geo_parse/modeling/detector/__init__.py", line 2, in <module>
    from .detectors import build_detection_model
  File "[path]/PGDP/geo_parse/modeling/detector/detectors.py", line 2, in <module>
    from .generalized_rcnn import GeneralizedRCNN
  File "[path]/PGDP/geo_parse/modeling/detector/generalized_rcnn.py", line 9, in <module>
    from ..backbone import build_backbone
  File "[path]/PGDP/geo_parse/modeling/backbone/__init__.py", line 2, in <module>
    from .backbone import build_backbone
  File "[path]/PGDP/geo_parse/modeling/backbone/backbone.py", line 7, in <module>
    from geo_parse.modeling.make_layers import conv_with_kaiming_uniform
  File "[path]/PGDP/geo_parse/modeling/make_layers.py", line 10, in <module>
    from geo_parse.layers import Conv2d
  File "[path]/PGDP/geo_parse/layers/__init__.py", line 10, in <module>
    from .nms import nms, ml_nms
  File "[path]/PGDP/geo_parse/layers/nms.py", line 3, in <module>
    from geo_parse import _C
ImportError: cannot import name '_C' from 'geo_parse' ([path]/PGDP/geo_parse/__init__.py)"

**Comment by mingliangzhang2018** [comment]
Maybe the error in building, please check if it is right when runing "python setup.py build develop --no-deps"

**Comment by SoniaQi** [comment]
> Maybe the error in building, please check if it is right when runing "python setup.py build develop --no-deps"

Thank you for the suggestion! Based on the feedback I think the error was caused by the absence of ‘geo_parse.csrc’ from the ‘packages’ configuration and some fucntions that got deprecated.
